// auto-generated by script 'get_ami_ids.sh'
ami_ids = {
  "us-east-1" = "ami-02354e95b39ca8dec" 
  "us-east-2" = "ami-07c8bc5c1ce9598c3" 
  "us-west-1" = "ami-05655c267c89566dd" 
  "us-west-2" = "ami-0873b46c45c11058d" 
}
