#!/bin/bash -e

OUTFILE="ami_ids.auto.tfvars"
rm -f ${OUTFILE}
touch ${OUTFILE}
echo "// auto-generated by script 'get_ami_ids.sh'" >> ${OUTFILE}
echo "ami_ids = {" >> ${OUTFILE}
REGIONS="us-east-1 us-east-2 us-west-1 us-west-2"

for REGION in ${REGIONS} ; do
  AMI_ID=$(aws ssm get-parameter --name /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2 --region ${REGION} | jq -r '.Parameter.Value')
  echo "  \"${REGION}\" = \"${AMI_ID}\" " >> ${OUTFILE}
done

echo "}" >> ${OUTFILE}
